name: Deploy Compatibility Layer

on:
  workflow_dispatch:
    inputs:
      quarter:
        description: 'Target quarter (e.g., 2025.Q1)'
        required: false
        type: string
      architectures:
        description: 'Architectures to build (comma-separated, or "all")'
        required: false
        default: 'all'
        type: string

env:
  CVMFS_REPOSITORY: software.lab.local

jobs:
  deploy-compat:
    runs-on: [self-hosted, linux, cvmfs-publisher, "${{ matrix.arch }}"]
    strategy:
      matrix:
        include:
          - arch: x86-64-v3
            cvmfs_arch: intel/haswell
            cflags: "-march=haswell -O2 -pipe"
            cpu_features: "AVX2 FMA BMI BMI2"
          - arch: x86-64-v4
            cvmfs_arch: intel/skylake_avx512
            cflags: "-march=skylake-avx512 -O2 -pipe"
            cpu_features: "AVX512F AVX512CD AVX512BW AVX512DQ AVX512VL"
      max-parallel: 1  # Sequential to avoid conflicts
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set Quarter
        id: set-quarter
        run: |
          if [[ -n "${{ inputs.quarter }}" ]]; then
            QUARTER="${{ inputs.quarter }}"
          else
            QUARTER=$(date +"%Y.Q$(( ($(date +%-m)-1)/3+1 ))")
          fi
          echo "Quarter: $QUARTER"
          echo "QUARTER=$QUARTER" >> $GITHUB_ENV
      
      - name: Check if should build this architecture
        id: check-build
        run: |
          ARCH_LIST="${{ inputs.architectures }}"
          CURRENT_ARCH="${{ matrix.cvmfs_arch }}"
          
          if [[ "$ARCH_LIST" == "all" ]] || echo "$ARCH_LIST" | grep -q "$CURRENT_ARCH"; then
            echo "should_build=true" >> $GITHUB_OUTPUT
          else
            echo "should_build=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy Gentoo Prefix
        if: steps.check-build.outputs.should_build == 'true'
        run: |
          set +e  # Don't exit on error immediately
          
          CVMFS_ARCH="${{ matrix.cvmfs_arch }}"
          CFLAGS="${{ matrix.cflags }}"
          CPU_FEATURES="${{ matrix.cpu_features }}"
          COMPAT_BASE="/cvmfs/$CVMFS_REPOSITORY/versions/$QUARTER/compat/linux/x86_64"
          
          echo "Deploying Gentoo Prefix"
          echo "Quarter: $QUARTER"
          echo "Architecture: $CVMFS_ARCH"
          echo "Optimization: $CFLAGS"
          echo "CPU Features: $CPU_FEATURES"
          
          # Start transaction
          echo "Starting CVMFS transaction..."
          sudo -u vagrant cvmfs_server abort -f $CVMFS_REPOSITORY 2>/dev/null || true
          
          if ! sudo -u vagrant cvmfs_server transaction $CVMFS_REPOSITORY; then
            echo "ERROR: Failed to start transaction"
            exit 1
          fi
          
          # Create prefix directory structure
          PREFIX_PATH="$COMPAT_BASE/$CVMFS_ARCH"
          echo "Creating Gentoo Prefix at: $PREFIX_PATH"
          
          sudo mkdir -p "$PREFIX_PATH"
          
          # Check if prefix already exists
          if [[ -f "$PREFIX_PATH/.prefix_complete" ]]; then
            echo "Gentoo Prefix already exists for $CVMFS_ARCH"
            
            # Just update if exists
            echo "Updating existing prefix..."
            bash compat-layer/updates/update-prefix.sh "$PREFIX_PATH" "$CVMFS_ARCH" "$CFLAGS"
          else
            echo "Bootstrapping new Gentoo Prefix for $CVMFS_ARCH"
            
            # Run bootstrap script
            bash compat-layer/bootstrap/bootstrap-prefix.sh \
              "$PREFIX_PATH" \
              "$CVMFS_ARCH" \
              "$CFLAGS" \
              "$CPU_FEATURES"
          fi
          
          # Run tests
          echo "Running validation tests..."
          if bash compat-layer/tests/test-prefix.sh "$PREFIX_PATH"; then
            echo "SUCCESS: All tests passed"
          else
            echo "WARNING: Some tests failed"
          fi
          
          # Publish transaction
          echo "Publishing changes..."
          if sudo -u vagrant cvmfs_server publish $CVMFS_REPOSITORY; then
            echo "Successfully published!"
            exit 0
          else
            echo "ERROR: Publish failed"
            sudo -u vagrant cvmfs_server abort -f $CVMFS_REPOSITORY
            exit 1
          fi

  summary:
    needs: deploy-compat
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Summary
        run: |
          echo "## Compatibility Layer Deployment" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [[ "${{ needs.deploy-compat.result }}" == "success" ]]; then
            echo "### Deployment Successful!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Gentoo Prefix has been deployed with architecture-specific optimizations." >> $GITHUB_STEP_SUMMARY
          else
            echo "### Deployment Failed" >> $GITHUB_STEP_SUMMARY
          fi
